### ISSUE TITLE
What's the data source of one-category multi-object QA pairs?

### ISSUE THREAD

**Issue by likanchuan** [jefferyZhan/Griffon#1]
Hi! Thanks for sharing your excellent work. I have a question on the one-category multi-object QA data used in the pre-training of griffon. 

I could understand that one-category one-object and multi-category multi-object data can be converted from vanilla REC or detection data, but how are one-category multi-object QA pairs obtained? Are they only from flickr30k or converted from detection data by querying one single label? I'm also curious about the statistics of data of various forms in the dataset.

Looking forward to your reply and best wishes!

**Comment by jefferyZhan** [comment]
Hi Kanchuan,

Thanks for your attention to our work. In this stage, the One Category with Multi Objects pairs are generated from phase grounding datasets including Flickr30K and GRIT, which we'll release later. We do not converted the detection data by querying one single label, as we already include the whole detection data as the Multi Categories with Multi Objects type. As for the statistic of different scenario data, we may illustrate it in the dataset page when making the dataset public in schedule.
