### ISSUE TITLE
RuntimeError:  Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0

### ISSUE THREAD

**Issue by dawn-ech** [jefferyZhan/Griffon#10]
Thanks for your great work! I am trying to run demo.sh on 2x 3090, but I get this error. The problem is located in `llava/model/multimodal_encoder.py ` `image_forward_outs = self.vision_tower(images, output_hidden_states=True)`. Here, `images` is on cuda:0, but I print its device in forward function (`transformers.models.clip.CLIPVisionModel.forward`), getting cuda:1. Could you give me some suggestions about it?

**Comment by jefferyZhan** [comment]
Hi @dawn-ech, 
This is caused by the auto setting in the weight loading code following llava. Add CUDA_VISIBLE_DEVICES setting will solve this, like:
`
CUDA_VISIBLE_DEVICES=0 bash demo/demo.sh demo/1vn.jpg "In this picture, identify and locate all the people in the front."
`

**Comment by dawn-ech** [comment]
@jefferyZhan Single GPU is not sufficient for 3090. `load 4 bit` is OK for me, but I need to at least two GPU for running. Can you run demo.sh by setting kwargs in llava.model.builder?
`kwargs = { 
        "device_map": "auto", 
        "max_memory": {i: "20GiB" for i in range(2)}, 
    }`
`CUDA_VISIBLE_DEVICES=0, 1 bash demo/demo.sh demo/1vn.jpg "In this picture, identify and locate all the people in the front."`

**Comment by dawn-ech** [comment]
This problem is solved. Thanks!
