### ISSUE TITLE
Typo in readme.

### ISSUE THREAD

**Issue by cooleel** [jefferyZhan/Griffon#11]
I suppose the first date should be `2014.3.15` ?

<img width="598" alt="Screenshot 2024-05-07 at 1 56 23 PM" src="https://github.com/jefferyZhan/Griffon/assets/10917451/1e2d974f-96e2-407f-b13d-f1ff2fcedca2">

**Comment by jefferyZhan** [comment]
Hi @cooleel,
Thank you for remind us of this error. We have fixed it.
