### ISSUE TITLE
Griffon v2

### ISSUE THREAD

**Issue by emersonium** [jefferyZhan/Griffon#12]
Hi, this sounds like a great improvement in your paper. Where can we test it, is there a demo ? I looked both here and in your HuggingFace and don't seem to see it ?
thanks

**Comment by jefferyZhan** [comment]
Hi @emersonium , thanks for your interest in our Griffon. We'll online the new version of Griffon next month with checkpoints and demo codes.

**Comment by Molly6** [comment]
Will Griffon v2 be open source in October? Thanks

**Comment by jefferyZhan** [comment]
Hi @Molly6 , as we’re continuously upgrading Griffon which draws a lot of attention, we delay the release of the codes and model of Griffon v2. As now we already have the next version, we consider to release the next version directly after the team confirmation. It’s planned    to be released in October. Thank you for your interest.

**Comment by jefferyZhan** [comment]
Hi, @Molly6 ! Sorry for the delay in releasing the latest Griffon-G because of the CVPR. We have released the latest Griffon-G and updated the inference codes. Welcome to try our new Griffon-G and follow our work.
