### ISSUE TITLE
Detection QA Dataset

### ISSUE THREAD

**Issue by kuaileqipaoshui** [jefferyZhan/Griffon#13]
It's great to see your excellent work. Currently, there is no QA Q&A on object detection data sets. Will you consider publishing QA Q&A data sets on detection? Or based on the current dataset such as refcoco, how to construct the corresponding question answering data?

**Comment by jefferyZhan** [comment]
Hi @kuaileqipaoshui
The QA construction process is a function we write in the Dataset class.  We have some samples in the paper to show the detection QA, which you may reference. We will release this together with our training code later.
