### ISSUE TITLE
Inquiry on mAP Implementation Details

### ISSUE THREAD

**Issue by JHYsama** [jefferyZhan/Griffon#16]
First, I would like to thank you for the inspiration your work has provided us. In your v1 paper, you mentioned testing the mAP on the MS COCO 2017 dataset, which includes both single-class multi-object and multi-class multi-object scenarios.

Could you please elaborate on how you designed the prompts for this? Specifically, when dealing with images containing different target objects, did you provide all 80 classes to the model at once, or did you communicate them in separate batches? Alternatively, did you directly query the model for localization based on known existing categories??

Thank you for your insights!

**Comment by jefferyZhan** [comment]
Hi @JHYsama,
Exactly we follow the standard evaluation for object detection. For MSCOCO, we provide all 80 classes at once, instead of querying the model one by one. We do not just query the model based on known existing categories as it conflicts with the original detection evaluation.

**Comment by JHYsama** [comment]
Thank you very much for your answer. I have a few more questions regarding the v1 paper, where it mentions that the score for object localization is calculated using the geometric mean of class probabilities and coordinates.

1. For example, if we have person-[0.491, 0.774, 0.892, 0.996] as the bbox, is the localization probability the product of all 20 tokens corresponding to these four coordinate values? Should we also include the symbols like ‘,’ and ‘[ ]’ in this product?

2.Are the token probabilities derived by applying softmax to the output_dict.score?

3.Additionally, is this approach sound? Since multiplying probabilities less than 1 would progressively reduce the score, even taking the 0.5 power would still yield a very small value.

Looking forward to your response. Good Luck!

**Comment by jefferyZhan** [comment]
1. the symbols are not included, but they do not influence the score for each object as they always have a score of approximately 1.0.
2. Softmax is applied.
3. The absolute value does not matter there. The score rank matters for objects detected in one image when evaluating.

**Comment by JHYsama** [comment]
I have replicated the results and implemented them according to this idea. Thank you very much for your help!
