### ISSUE TITLE
inference problem

### ISSUE THREAD

**Issue by Qiqi224** [jefferyZhan/Griffon#19]
Hello！Your work is perfect.I miss some problems when I run the demo.sh, my error are as follows.

There are many warnings like this:
warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '
/home/shanboqi/anaconda3/envs/griffon/lib/python3.10/site-packages/torch/nn/modules/module.py:2025: UserWarning: for vision_model.post_layernorm.weight: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)

and a warning like this:
WARNING:root:Some parameters are on the meta device device because they were offloaded to the cpu.

and at last, there is an error:
Traceback (most recent call last):
  File "/home/shanboqi/griffon-master/llava/eval/run_llava.py", line 124, in <module>
    eval_model(args)
  File "/home/shanboqi/griffon-master/llava/eval/run_llava.py", line 46, in eval_model
    tokenizer, model, image_processor, context_len = load_pretrained_model(args.model_path, args.model_base, model_name)
  File "/home/shanboqi/anaconda3/envs/griffon/lib/python3.10/site-packages/llava/model/builder.py", line 147, in load_pretrained_model
    vision_tower.to(device=model.device, dtype=torch.float16)
  File "/home/shanboqi/anaconda3/envs/griffon/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1152, in to
    return self._apply(convert)
  File "/home/shanboqi/anaconda3/envs/griffon/lib/python3.10/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/home/shanboqi/anaconda3/envs/griffon/lib/python3.10/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/home/shanboqi/anaconda3/envs/griffon/lib/python3.10/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/shanboqi/anaconda3/envs/griffon/lib/python3.10/site-packages/torch/nn/modules/module.py", line 825, in _apply
    param_applied = fn(param)
  File "/home/shanboqi/anaconda3/envs/griffon/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1150, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!

Could you help me with these problems, thank you very much!

**Comment by jefferyZhan** [comment]
Hi @Qiqi224 ,
If using the latest Griffon-G model, you should also update the codes to the latest version. According to the log, you are still using the previous version of the inference code, which does not support the latest model. 
For the first warning "warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '", this is caused by the pytorch and transformers version. It will not affect the final result, so we do not fix or hide this warning in the code.

**Comment by Qiqi224** [comment]
> Hi @Qiqi224 , If using the latest Griffon-G model, you should also update the codes to the latest version. According to the log, you are still using the previous version of the inference code, which does not support the latest model. For the first warning "warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '", this is caused by the pytorch and transformers version. It will not affect the final result, so we do not fix or hide this warning in the code.

Hi, I am happy you can help me. I download the Griffon-v1 model from huggingface, and I follow your tutorial to deal with both the Griffon and Clip checkpoints, then I run demo.sh and meet the error above, I don't know how to solve the error.

**Comment by jefferyZhan** [comment]
We just follow the v1 [usage.](https://github.com/jefferyZhan/Griffon/tree/faca54883a649693d5e20c42dabc2a8e35cee759) to run the inference codes and get the correct response without meeting the above error. It seems like the vision tower inited is not loaded correctly with weights. Maybe you can check the environment version, the part you might have modified, and the way you run the demo.sh to solve this error.
